apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 1m
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      version: '6.15.3'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      reconcileStrategy: Revision
  values:
    # https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
    config:
      clients:
        - url: http://loki-gateway/loki/api/v1/push
          tenant_id: 1
      snippets:
        extraRelabelConfigs:
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_uid
            target_label: pod_uid
    extraArgs:
      - "-client.external-labels=cluster=istio-test"
    tolerations:
      - operator: Exists
    serviceMonitor:
      enabled: true
