apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookinfo
resources:
  - namespace.yaml
  - resources.yaml
  - bookinfo-gateway.yaml
  - destination-rules.yaml
#  - traffic-shift-v1.yaml
  - traffic-shift-v1-v3.yaml
