apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  schedule: "*/1 * * * *"  # runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo "Hello from the cron job at $(date)"
          restartPolicy: OnFailure
