apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: '1.25.0'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: '1.25.0'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1m
  values:
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi

    meshConfig:
      accessLogFile: "/dev/stdout"
      accessLogEncoding: TXT
      accessLogFormat: |
      "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS%
\"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\"
\"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER_RAW% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"

      #   {
      #     "start_time": "%START_TIME%",
      #     "method": "%REQ(:METHOD)%",
      #     "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
      #     "protocol": "%PROTOCOL%",
      #     "request_id": "%REQ(X-REQUEST-ID)%",
      #     "user_agent": "%REQ(USER-AGENT)%",
      #     "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
      #     "response_code": "%RESPONSE_CODE%",
      #     "bytes_received": "%BYTES_RECEIVED%",
      #     "bytes_sent": "%BYTES_SENT%",
      #     "duration_ms": "%DURATION%",
      #     "upstream_cluster": "%UPSTREAM_CLUSTER%",
      #     "upstream_host": "%UPSTREAM_HOST%"
      #   }

    global:
      proxy:
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
      # imagePullSecrets:
      #   - test
