apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: '1.25.0'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: '1.25.0'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1m
  values:
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi

    meshConfig:
      accessLogFile: "/dev/stdout"
      accessLogEncoding: JSON
      accessLogFormat:  |
        {
          "start_time": "%START_TIME%",
          "method": "%REQ(:METHOD)%",
          "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
          "protocol": "%PROTOCOL%",
          "request_id": "%REQ(X-REQUEST-ID)%",
          "response_code": "%RESPONSE_CODE%",
          "req_forwarded":"%REQ(X-FORWARDED-FOR)%",
          "req_user":"%REQ(USER-AGENT)%",
          "UPSTREAM_HOST": "%UPSTREAM_HOST%",
          "upstream": "%UPSTREAM_CLUSTER_RAW%",
          "bytes_sent": "%BYTES_SENT%",
          "bytes_received": "%BYTES_RECEIVED%",
          "duration": "%DURATION%"
        }

    global:
      proxy:
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
      # imagePullSecrets:
      #   - test
