apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            mode: CLIENT
            metric: ALL_METRICS
          tagOverrides:
            source_app:
              value:  "has(source.labels['app'].value) ? source.labels['app'].value : 'testooo'"
              #value: "has(source.labels['app.kubernetes.io/name'])? source.labels['app.kubernetes.io/name'] : 'test'"
              #value: 'has(node.metadata["LABELS"]["app.kubernetes.io/name"]) ? node.metadata["LABELS"]["app.kubernetes.io/name"] : "test"'
              operation: UPSERT
        - match:
            mode: SERVER
            metric: ALL_METRICS
          tagOverrides:
            source_app:
              value: "has(source.labels['app'].value) ? source.labels['app'].value : 'testooo'"
              #value:  "has(source.labels['app.kubernetes.io/name'])? source.labels['app.kubernetes.io/name'] : 'test'"
              operation: UPSERT
              #value: 'has(node.metadata["LABELS"]["app.kubernetes.io/name"]) ? node.metadata["LABELS"]["app.kubernetes.io/name"] : "test"'
