apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            mode: CLIENT
            metric: ALL_METRICS
          tagOverrides:
            source_app:
              value: "has(upstream_peer.labels['app'].value) ? upstream_peer.labels['app'].value : 'test'"
              operation: UPSERT
        - match:
            mode: SERVER
            metric: ALL_METRICS
          tagOverrides:
            source_app:
              value: "has(downstream_peer.labels['app'].value) ? downstream_peer.labels['app'].value : 'test'"
              operation: UPSERT
