apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            mode: CLIENT
            metric: ALL_METRICS
          tagOverrides:
            source_app:
              value:  "has(source.labels['app']) ? source.labels['app'] : 'testooo'"
              operation: UPSERT
        - match:
            mode: SERVER
            metric: ALL_METRICS
          tagOverrides:
            source_app:
              value: "has(source.labels['app']) ? source.labels['app'] : 'testooo'"
              operation: UPSERT
