apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            metric: "REQUEST_COUNT"
            mode: CLIENT_AND_SERVER
          tagOverrides:
            source_app:
              value: source.labels["app.kubernetes.io/name"] | source.labels["app"] | "test"
              operation: UPSERT
            destination_app:
              value: destination.labels["app.kubernetes.io/name"] | destination.labels["app"]  | "test"
              operation: UPSERT
