apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - tagOverrides:
            source_app:
              operation: UPSERT
              value: "node.metadata['LABELS']['app.kubernetes.io/name']"
          match:
            mode: CLIENT
            metric: ALL_METRICS
        - tagOverrides:
            source_app:
              operation: UPSERT
              value: "downstream_peer.labels['app.kubernetes.io/name'].value"
          match:
            mode: SERVER
            metric: ALL_METRICS
