apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            mode: CLIENT
            metric: ALL_METRICS
          tagOverrides:
            source_app:
              value: value: "has(filter_state['upstream_peer']['app.kubernetes.io/name']) ? filter_state['upstream_peer']['app.kubernetes.io/name'] : 'test'"
        - match:
            mode: SERVER
            metric: ALL_METRICS
          tagOverrides:
            source_app:
              operation: UPSERT
              value: value: "has(filter_state['downstream_peer']['app.kubernetes.io/name']) ? filter_state['downstream_peer']['app.kubernetes.io/name'] : 'test'"
