apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  metrics:
    - overrides:
        - match:
            metric: "ALL_METRICS"
          tagOverrides:
            source_app:
              value: 'source.labels["app.kubernetes.io/name"] | source.labels["app"] | "test"'
              operation: UPSERT
            destination_app:
              value: 'destination.labels["app.kubernetes.io/name"] | destination.labels["app"]  | "test"'
              operation: UPSERT
      providers:
        - name: prometheus
