apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-config
  namespace: observability
data:
  values.yaml: |

    prometheus:
      serviceMonitor:
        selfMonitor: false
      prometheusSpec:
        retention: 14d
        # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3046
        serviceMonitorSelectorNilUsesHelmValues: true
        serviceMonitorSelector: {}
        # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3069
        podMonitorSelectorNilUsesHelmValues: true
        podMonitorSelector: {}
        # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3113
        scrapeConfigSelectorNilUsesHelmValues: true
        scrapeConfigSelector: {}
        # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3866
        ruleSelectorNilUsesHelmValues: false
        # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3091
        probeSelectorNilUsesHelmValues: true


    # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L163
    # Example: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.container_memory_working_set_bytes.yaml#L30C50-L30C77
    defaultRules:
      create: false

    alertmanager:
      enabled: true
      serviceMonitor:
        selfMonitor: false

    grafana:
      enabled: true
      assertNoLeakedSecrets: false
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.observability:3100
          editable: true
          jsonData:
            maxLines: 10000
            minRefreshInterval: 5s

    prometheusOperator:
      kubeletService:
        enabled: true
      serviceMonitor:
        selfMonitor: false

    # disable metrics unavailable for managed Kubernetes distributions (GKE, EKS, AKS)
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false

    # disable subcharts to stop scraping thru this instance

    kubeApiServer:
      enabled: true
    kubelet:
      enabled: true
    coreDns:
      enabled: false

    kubeDns:
      enabled: false
    kubeProxy:
      enabled: true
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
