# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: traffic-mngmt-demo
#   namespace: flux-system
# spec:
#   interval: 1m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   path: ./demos/traffic-mngmt
#   prune: true
