{
 "title": "Istio Control Plane Dashboard",
 "description": "Istio Control Plane Dashboard version 1.23.6",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Deployed Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pilot Versions",
   "type": "timeseries",
   "description": "Version number of each running instance",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(istio_build{component=\"pilot\"}) by (tag)",
     "legendFormat": "Version ({{tag}})"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of each running instance",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{container=\"discovery\", pod=~\"istiod-.*\"}\n)",
     "legendFormat": "Container ({{pod}})"
    },
    {
     "expr": "sum by (pod) (\n  go_memstats_stack_inuse_bytes{app=\"istiod\"}\n)",
     "legendFormat": "Stack ({{pod}})"
    },
    {
     "expr": "sum by (pod) (\n  go_memstats_heap_inuse_bytes{app=\"istiod\"}\n)",
     "legendFormat": "Heap (In Use) ({{pod}})"
    },
    {
     "expr": "sum by (pod) (\n  go_memstats_heap_alloc_bytes{app=\"istiod\"}\n)",
     "legendFormat": "Heap (Allocated) ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "timeseries",
   "description": "Details about memory allocations",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    go_memstats_alloc_bytes_total{app=\"istiod\"}\n  [$__rate_interval])\n)",
     "legendFormat": "Bytes ({{pod}})"
    },
    {
     "expr": "sum by (pod) (\n  rate(\n    go_memstats_mallocs_total{app=\"istiod\"}\n  [$__rate_interval])\n)",
     "legendFormat": "Objects ({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of each running instance",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(\n    container_cpu_usage_seconds_total{container=\"discovery\", pod=~\"istiod-.*\"}\n  [$__rate_interval])\n)",
     "legendFormat": "Container ({{pod}})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Goroutine count for each running instance",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  go_goroutines{app=\"istiod\"}\n)",
     "legendFormat": "Goroutines ({{pod}})"
    }
   ]
  },
  { "title": "Push Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "XDS Pushes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (type) (\n  irate(\n    pilot_xds_pushes{}\n  [$__rate_interval])\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "description": "Size of each xDS push.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "sum by (type, event) (\n  rate(\n    pilot_k8s_reg_events{}\n  [$__rate_interval])\n)",
     "legendFormat": "{{event}} {{type}}"
    },
    {
     "expr": "sum by (type, event) (\n  rate(\n    pilot_k8s_cfg_events{}\n  [$__rate_interval])\n)",
     "legendFormat": "{{event}} {{type}}"
    },
    {
     "expr": "sum by (type) (\n  rate(\n    pilot_push_triggers{}\n  [$__rate_interval])\n)",
     "legendFormat": "Push {{type}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Total number of XDS connections\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{cluster_name=\"xds-grpc\"})",
     "legendFormat": "Connections (client reported)"
    },
    { "expr": "sum(pilot_xds{})", "legendFormat": "Connections (server reported)" }
   ]
  },
  {
   "title": "Push Errors",
   "type": "timeseries",
   "description": "Number of push errors. Many of these are at least potentional fatal and should be explored in-depth via Istiod logs.\nNote: metrics here do not use rate() to avoid missing transition from \"No series\"; series are not reported if there are no errors at all.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (type) (\n  pilot_total_xds_rejects{}\n)",
     "legendFormat": "Rejected Config ({{type}})"
    },
    {
     "expr": "pilot_total_xds_internal_errors{}",
     "legendFormat": "Internal Errors"
    },
    {
     "expr": "pilot_xds_push_context_errors{}",
     "legendFormat": "Push Context Errors"
    }
   ]
  },
  {
   "title": "Push Time",
   "type": "heatmap",
   "description": "Count of active and pending proxies managed by each instance.\nPending is expected to converge to zero.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(pilot_xds_push_time_bucket{}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Push Size",
   "type": "heatmap",
   "description": "Size of each xDS push.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(pilot_xds_config_size_bytes_bucket{}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Webhooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Validation",
   "type": "timeseries",
   "description": "Rate of XDS push operations, by type. This is incremented on a per-proxy basis.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    galley_validation_passed{}\n  [$__rate_interval])\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(\n  rate(\n    galley_validation_passed{}\n  [$__rate_interval])\n)",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Injection",
   "type": "timeseries",
   "description": "Size of each xDS push.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    sidecar_injection_success_total{}\n  [$__rate_interval])\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(\n  rate(\n    sidecar_injection_failure_total{}\n  [$__rate_interval])\n)",
     "legendFormat": "Failure"
    }
   ]
  }
 ]
}